Repository book-hub-umsp/book-hub-app, pull requests merged in 2024-11, with the labels that each got.

#10 Fix deploy actions
  .github/workflows/deploy-docker.yml
  .github/workflows/deploy-version.yml
  .github/workflows/issue.yml
Labels: patсh

#11 Force deploy action
  .github/workflows/issue.yml
Labels: patch

#12 Fixes for deploy action
  docker/Dockerfile
Labels: patch

#14 #9 Add react-query and mantine
  apps/host/next.config.js
  apps/host/postcss.config.cjs
  apps/host/src/app/global.css
  apps/host/src/app/layout.tsx
  apps/host/src/app/page.tsx
  libs/shared/queries/.babelrc
  libs/shared/queries/README.md
  libs/shared/queries/project.json
  libs/shared/queries/src/index.ts
  libs/shared/queries/src/lib/getQueryClient.ts
  libs/shared/queries/src/lib/index.ts
  libs/shared/queries/tsconfig.json
  libs/shared/queries/tsconfig.lib.json
  nx.json
  package-lock.json
  package.json
  tsconfig.base.json
Labels: patch

#18 #7 add authorization
  apps/host/specs/index.spec.tsx
  apps/host/src/app/api/auth/[...nextauth]/route.ts
  apps/host/src/app/layout.tsx
  apps/host/src/app/page.tsx
  libs/configs/auth/README.md
  libs/configs/auth/project.json
  libs/configs/auth/src/index.ts
  libs/configs/auth/src/lib/auth.ts
  libs/configs/auth/tsconfig.json
  libs/configs/auth/tsconfig.lib.json
  libs/features/auth-button/.babelrc
  libs/features/auth-button/README.md
  libs/features/auth-button/project.json
  libs/features/auth-button/src/index.ts
  libs/features/auth-button/src/lib/AuthButton.tsx
  libs/features/auth-button/src/lib/index.ts
  libs/features/auth-button/tsconfig.json
  libs/features/auth-button/tsconfig.lib.json
  package-lock.json
  package.json
  tsconfig.base.json
Labels: minor
